#!/bin/bash
# Builds a 

if [ $# -ne 4 ]; 
then 
    printf "Quick check for package randasm -- build & assemble a bunch of random source files.\n\n"
    printf "usage: randasm-quickcheck.sh <target> <assembler executable> <# instr.> <# trials>\n\n"
    exit 1
fi

mkdir -p output
rm output/*

printf "\033[1;34mrandasm -- quickcheck for target '$1'\033[0m\n"
for i in `seq 1 $4`;
do
    printf "randasm - $1 - building & assembling check #$i out of $4...\n"
    randasm -n $3 --target $1 > output/trial$i.asm
    $2 output/trial$i.asm
    rc=$?; if [[ $rc != 0 ]]; then printf "\n\033[1;32mAssembly failed, check terminated.\033[0m\n"; exit $rc; fi
done 
